# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20170217_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
